### ISSUE TITLE
Change layout animation after init/set

### ISSUE THREAD

**Issue by cryinrain69** [MLSDev/AnimatedRecyclerView#3]
Hi.
First, thank you so much for good app!
After i init AnimatedRecyclerView, i want change animation by click button.
How can i do it ?

**Comment by SerhiyPetrosyuk** [comment]
Hi @cryinrain69 
You can init your recyclerView again with a new animation. 
Note! Don't init your items adapter if it is already was, just use one you already have.

Sorry for the late replay.
